loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  compactor:
    apply_retention_interval: 1h
    compaction_interval: 5m
    retention_delete_worker_count: 500
    retention_enabled: true
    shared_store: s3
    working_directory: /data/compactor
  config:  
      schema_config:
        configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            period: 24h
            prefix: loki_index_
        
      storage_config:
        aws:
          region: us-east-1
          bucketnames: loki-centralize-logging-bucket
          s3forcepathstyle: false
        boltdb_shipper:
          shared_store: s3
          cache_ttl: 24h
  serviceAccount:
    create: true
    name: loki-sa
    annotations:
       eks.amazonaws.com/role-arn: "arn:aws:iam::360286454260:role/loki-s3-service-account-role"
  write:
     replicas: 2
  read:
    replicas: 1

# grafana:
#     enabled: true
#     sidecar:
#       datasources:
#         enabled: true
#     image:
#       tag:  7.5.17
#     grafana.ini:
#       users:
#         default_theme: dark