apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: monitor-app-cert-isssuer
  namespace: monitor-app
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: alam.akbar1989@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: monitor-app-cert-isssuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx       
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitor-app-cert
  namespace: monitor-app
spec:
  secretName: monitor-app-cert-secret
  issuerRef:
    name: monitor-app-cert-isssuer
    kind: ClusterIssuer
  commonName: akbaralam.me
  dnsNames:
  - akbaralam.me 
