---
apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secret
data:
  MYSQL_DB_HOST: bXlzcWwtc3RzLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  MYSQL_DB_NAME: YXJ0aWNsZQ==
  MYSQL_DB_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DB_USER: dXNlcg==
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: script0kid/article-backend:v0
        ports:
          - containerPort: 5000
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-api-secret
                key: MYSQL_DB_HOST
          - name: MYSQL_DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-api-secret
                key: MYSQL_DB_NAME
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-api-secret
                key: MYSQL_DB_PASSWORD
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-api-secret
                key: MYSQL_DB_USER
        # volumeMounts: 
        #   -  name: backend-api-volume
        #      mountPath: /app
      volumes:
        -  name: backend-api-volume
           emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-svc
  labels:
    app: backend-api-svc
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-isssuer
  name: backend-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: api.akbaralam.me
    http:
      paths:
      - backend:
          service:
            name: backend-api-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts: 
    - api.akbaralam.me
    secretName: api-cert-secret