apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: api-cert-isssuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: alam.akbar1989@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: api-cert-secret
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx       
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certificate
spec:
  secretName: api-cert-secret
  issuerRef:
    name: api-cert-isssuer
    kind: ClusterIssuer
  commonName: api.akbaralam.me
  dnsNames:
  - api.akbaralam.me